version: "2"
run:
  tests: true
linters:
  enable:
    - contextcheck
    - copyloopvar
    - errorlint
    - exhaustive
    - exptostd
    - gocritic
    - importas
    - misspell
    - nakedret
    - nilnesserr
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - testifylint
    - unconvert
    - usetesting
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    rules:
      - linters:
          - revive
        path: ^internal/parser/utils/
        text: "var-naming: avoid meaningless package names"
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/prymitive/karma
