run:
  timeout: 5m

output:
  sort-results: true

linters:
  enable:
    - gofumpt
    - goimports
    - revive
    - misspell
    - promlinter
    - errorlint
    - predeclared
    - exhaustive
    - importas
    - nakedret
    - prealloc
    - unconvert
    - testifylint
    - copyloopvar
    - exptostd
    - nilnesserr
    - usetesting

issues:
  max-same-issues: 0

linters-settings:
  goimports:
    local-prefixes: github.com/prymitive/karma
  gofumpt:
    extra-rules: true
