run:
  deadline: 5m

output:
  sort-results: true

linters:
  enable:
    - depguard
    - gofumpt
    - goimports
    - revive
    - misspell
    - staticcheck
    - promlinter
    - tenv
    - errorlint
    - exportloopref
    - predeclared

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages-with-error-message:
      - io/ioutil: "Use corresponding 'os' or 'io' functions instead."
  goimports:
    local-prefixes: github.com/prymitive/karma
  gofumpt:
    extra-rules: true
  govet:
    enable:
      - assign
      - atomic
      - atomicalign
      - fieldalignment
      - unusedresult
      - unreachable
      - unmarshal
      - tests
      - structtag
      - sortslice
      - sigchanyzer
      - lostcancel
      - loopclosure
      - httpresponse
      - errorsas
      - deepequalerrors
      - copylock
      - composite
      - bools
