run:
  deadline: 5m
  skip-files:
    - bindata_assetfs.go

linters:
  enable:
    - golint
    - dupl
    - goconst
    - scopelint
    - maligned
    - goimports
    - goconst
    - misspell
    - unparam
    - nakedret
    - prealloc

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  dupl:
    threshold: 200
