FROM alpine:latest
COPY --from=lmierzwa/unsee:latest /unsee /unsee
RUN adduser -D unsee
USER unsee
ENV LOG_CONFIG=false
ENV ALERTMANAGER_INTERVAL=2400h
ENV ALERTMANAGER_URI=file:///mock
ENV LABELS_COLOR_UNIQUE="@receiver instance cluster"
ENV LABELS_COLOR_STATIC="job"
ENV FILTERS_DEFAULT="@receiver=by-cluster-service"
COPY internal/mock/0.15.2 /mock
CMD /unsee
