FROM node:10.13.0-alpine as nodejs-builder
RUN apk add --update make git
COPY . /karma
RUN make -C /karma ui

FROM golang:1.11.2-alpine as go-builder
COPY --from=nodejs-builder /karma /go/src/github.com/prymitive/karma
ARG VERSION
RUN apk add --update make git
RUN CGO_ENABLED=0 make -C /go/src/github.com/prymitive/karma VERSION="${VERSION:-dev}" karma

FROM gcr.io/distroless/base
COPY --from=go-builder /go/src/github.com/prymitive/karma/karma /karma
COPY --from=go-builder /bin/sh /bin/sh
COPY --from=go-builder /usr/bin/wget /bin/wget

HEALTHCHECK --interval=25s --timeout=10s --start-period=15s CMD /bin/wget -q -Y off http://localhost:8080 -O /dev/null > /dev/null 2>&1

EXPOSE 8080
ENTRYPOINT ["/karma"]
