# There are security implications when using this image, as the busybox binary is added
# to facilite Docker container HEALTHCHECK, at least until the following issue is addressed:
#   https://github.com/GoogleContainerTools/jib/issues/676
# As the attack surface increaces in containers exposing a web service and a containing a
# shell, use this image only on a protected network. Use of Caddy, Traefik, or other proxy
# for further protecting this image through a layer of indirection is recommended.
# See https://github.com/swarmstack/swarmstack for an example Docker compose stack for Caddy
# and Karma.

FROM node:10.13.0-alpine as nodejs-builder
RUN apk add --update make git
COPY . /karma
RUN make -C /karma ui

FROM golang:1.11.2-alpine as go-builder
COPY --from=nodejs-builder /karma /go/src/github.com/prymitive/karma
ARG VERSION
RUN apk add --update make git
RUN CGO_ENABLED=0 make -C /go/src/github.com/prymitive/karma VERSION="${VERSION:-dev}" karma

FROM gcr.io/distroless/base:debug as busybox

# Compress Caddy with UPX
#
FROM debian:stable as compress

# curl, tar
RUN apt-get update && apt install -y --no-install-recommends \
    tar \
    xz-utils \
    curl \
    ca-certificates

# get official upx binary
RUN curl --silent --show-error --fail --location -o - \
    "https://github.com/upx/upx/releases/download/v3.95/upx-3.95-amd64_linux.tar.xz" \
    | tar --no-same-owner -C /usr/bin/ -xJ \
    --strip-components 1 upx-3.95-amd64_linux/upx

# copy and compress
COPY --from=go-builder /go/src/github.com/prymitive/karma/karma /karma
COPY --from=busybox /busybox/busybox /busybox
RUN /usr/bin/upx --ultra-brute /karma
RUN /usr/bin/upx --ultra-brute /busybox

# test
RUN /karma --version

FROM gcr.io/distroless/base
COPY --from=compress /karma /karma
COPY --from=compress /busybox /bin/sh
COPY --from=compress /busybox /bin/wget

HEALTHCHECK --interval=25s --timeout=10s --start-period=15s CMD /bin/wget -q -Y off http://localhost:8080 -O /dev/null > /dev/null 2>&1

EXPOSE 8080
ENTRYPOINT ["/karma"]
