apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: karma
commonLabels:
  app.kubernetes.io/name: karma
resources:
- deploy/karma.yaml
configMapGenerator:
- files:
  - karma.yaml=docs/example.yaml
  name: karma
