skip-missing: true
ignores:
  # deps
  - bootstrap
  - bootswatch
  - sass
  - typeface-open-sans
  - prettier
  - react-scripts
  - typescript
  # devDeps
  - "@types/jest"
  - "@types/node"
  - "@storybook/preset-create-react-app"
  - "@storybook/builder-webpack5"
  - "@storybook/manager-webpack5"
  - "purgecss"
  - "eslint-plugin-jest"
