skip-missing: true
ignores:
  # deps
  - bootstrap
  - bootswatch
  - sass
  - typeface-open-sans
  - babel-loader
  # devDeps
  - "@types/jest"
  - "@types/node"
  - "@storybook/preset-create-react-app"
  - depcheck
