skip-missing: true
ignores:
  # deps
  - bootstrap
  - bootswatch
  - sass
  - typeface-open-sans
  - prettier
  - "@popperjs/core"
  - react-scripts
  - typescript
  # devDeps
  - "@types/jest"
  - "@types/node"
  - "@percy/storybook"
  - "@storybook/preset-create-react-app"
