skip-missing: true
ignores:
  # deps
  - bootstrap
  - bootswatch
  - sass
  - typeface-open-sans
  - prettier
  - react-scripts
  - typescript
  # devDeps
  - "@types/jest"
  - "@types/node"
  - "purgecss"
  - "eslint-plugin-jest"
  - "node-fetch"
  - "@babel/plugin-proposal-private-property-in-object"
