skip-missing: true
ignores:
  # deps
  - bootstrap
  - bootswatch
  - sass
  - typeface-open-sans
  - prettier
  - vite
  - typescript
  # devDeps
  - "csstype"
  - "@types/jest"
  - "@types/node"
  - "eslint-plugin-jest"
  - "node-fetch"
  - identity-obj-proxy
  - jest
  - jest-fetch-mock
  - terser
