name: Lint Actions

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1.34.2
