name: Automerge

on:
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-20.04
    steps:
      - name: automerge
        if: github.event.context == 'Mergeable'
        uses: "pascalgn/automerge-action@v0.13.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_REPO_TOKEN }}"
          MERGE_LABELS: "automerge,!WIP"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_FORKS: "false"
          MERGE_DELETE_BRANCH: "true"
          UPDATE_LABELS: "automerge,!WIP"
          UPDATE_METHOD: "rebase"
