name: Maintenance

on:
  schedule:
    - cron: "0 20 * * 1"

jobs:
  go-mod-upgrades:
    name: Upgrade all Go modules
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4

      - name: Mock web assets
        run: make mock-assets

      - name: Upgrade all Go modules
        run: go get -u ./...

      - name: Run go mod tidy
        run: go mod tidy

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          author: "Łukasz Mierzwa <l.mierzwa@gmail.com>"
          commit-message: "chore(backend): upgrade all Go modules"
          branch: go-mod-upgrades
          delete-branch: true
          title: "chore(backend): upgrade all Go modules"
          labels: automerge

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
