name: Node version

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile

jobs:
  version-sync:
    name: Synchronise node-version
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get Node version from Dockerfile
        run: |
          echo "NODE_VERSION=$(grep 'FROM node:' Dockerfile | cut -d ':' -f2 | cut -d '-' -f1 | tr -d '\n')" >> $GITHUB_ENV

      - name: Synchronise Node version in actions
        run: |
          sed -i -E s/'([\ \t]+)node-version: .+'/'\1node-version: ${{ env.NODE_VERSION }}'/g .github/workflows/*
          sed -i -E s/'([\ \t]+)"node": .+'/'\1"node": "${{ env.NODE_VERSION }}"'/g ui/package.json

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          author: "Łukasz Mierzwa <l.mierzwa@gmail.com>"
          commit-message: "chore(actions): use latest Node version"
          branch: version-sync-node
          delete-branch: true
          title: "chore(actions): use latest Node version"
          labels: automerge

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
